name: Terraform

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  plan:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Initialise project and view terraform plan
        run: |
          cd IAC/terraform 
          terraform fmt
          terraform init 
          terraform plan
          terraform apply --auto-approve=true